version: '3.7'
services:
  php:
    container_name: php
    build: ./docker/php
    ports:
      - 88:8000
      - 80:80
    volumes:
      - ./docker/php/app:/app/
    networks:
      - site
      - mysql
    env_file:
      # Use .env with secure db credentials (needs creating), ignored by git
      - '.env.php.prod'
    depends_on:
      - mysql
    restart: always
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      # Use .env with secure db credentials (needs creating), ignored by git
      - '.env.mysql.prod'
    networks:
      - mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - mysql
    restart: always
    ports:
      - 8080:80
    env_file:
      # Use .env with secure db credentials (needs creating), ignored by git
      - '.env.pma.prod'
    networks:
      - site
      - mysql

networks:
  site:
  mysql:
volumes:
  db_data: